package smartindiahackathon;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;

public class pdf 
{
    static String a,id,ty,date,tn,name;
    private static Font cFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.BOLD,BaseColor.RED);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.NORMAL, BaseColor.GREEN);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.NORMAL, BaseColor.RED);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    public pdf(String a,String id,String name,String ty,String tn,String date)
    {
        this.a=a;
        this.id=id;
        this.name=name;
        this.ty=ty;
        this.tn=tn;
        this.date=date;
        create_pdf();
    }
    public void create_pdf()
    {
        try
        {
        String file=a+"\\Recipt.pdf";
        Document doc = new Document();
        PdfWriter.getInstance(doc,new FileOutputStream(file));
        doc.open();
        addMessage(doc);
        
        doc.close();
        System.out.println("finished");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    public static void main(String ar[])
    {
    }
    public static void addMessage(Document doc)throws DocumentException, BadElementException, IOException
    {
        Paragraph para=new Paragraph();
        addEmptyLine(para,1);
        para.add(new Paragraph("Government of Andhra Pradesh", redFont));
        para.setAlignment(Element.ALIGN_CENTER);
        
        Image ima=Image.getInstance("D:\\andhra.png");
        ima.setAbsolutePosition(200f,500f);
        doc.add(ima);
        addEmptyLine(para, 1);
        
        para.add(new Paragraph("Report Generated By: Govenment Of Andhra Pradesh, " + new Date(), smallBold));
        addEmptyLine(para,1);
        para.add(new Paragraph("This certify that the"+name+" organization has added a new livestock in his "
                + "husbandry.It is a humble request to please reflect this in formation in your records"
        +" It Will be of great help."));
        addEmptyLine(para, 3);
        doc.add(para);
        PdfPTable t=new PdfPTable(2);
        PdfPCell c=new PdfPCell(new Phrase("Categories",cFont));
        c.setBorderColor(BaseColor.BLUE);
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
        c=new PdfPCell(new Phrase("Details",cFont));
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
        t.setHeaderRows(1);
        t.addCell("Owner ID");
        t.addCell(id);
        t.addCell("Owner Organization Name");
        t.addCell(name);
        t.addCell("Livestock Type");
        t.addCell(ty);
        t.addCell("Tag of Livestock");
        t.addCell(tn);
        t.addCell("Birth Date");
        t.addCell(date);
        doc.add(t);
        para=new Paragraph(" ");
        addEmptyLine(para,2);
        
        para=new Paragraph("Thanking You"); 
        addEmptyLine(para,2);
        para=new Paragraph("Owner Signature");
        doc.add(para);
    }

    private static void addEmptyLine(Paragraph para, int n) {
        for (int i = 0; i < n; i++) 
            para.add(new Paragraph(" "));
    }
}
