package smartindiahackathon;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;

public class pdf1 
{
    static String a,i,ty,pn,tn,nn;
    static int p;
    private static Font cFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.BOLD,BaseColor.RED);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.NORMAL, BaseColor.GREEN);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.NORMAL, BaseColor.RED);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    public pdf1(String a,String i,String nn,String ty,String tn,String pn,int p)
    {
        this.a=a;
        this.i=i;
        this.nn=nn;
        this.ty=ty;
        this.tn=tn;
        this.pn=pn;
        this.p=p;
        System.out.println(nn);
        create_pdf();
    }
    public void create_pdf()
    {
        try
        {
        String file=a+"\\Recipt.pdf";
        Document doc = new Document();
        PdfWriter.getInstance(doc,new FileOutputStream(file));
        doc.open();
        addMessage(doc);
        
        doc.close();
        System.out.println("finished");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    public static void main(String ar[])
    {
    }
    public static void addMessage(Document doc)throws DocumentException, BadElementException, IOException
    {
        Paragraph para=new Paragraph();
        addEmptyLine(para,1);
        para.add(new Paragraph("Government of Andhra Pradesh", redFont));
        para.setAlignment(Element.ALIGN_CENTER);
        
        Image ima=Image.getInstance("D:\\andhra.png");
        ima.setAbsolutePosition(200f,500f);
        doc.add(ima);
        addEmptyLine(para, 1);
        
        para.add(new Paragraph("Report Generated By: Govenment Of Andhra Pradesh, " + new Date(), smallBold));
        addEmptyLine(para,1);
        para.add(new Paragraph("This certify that Mr."+pn+" has tranfered his livestock to Mr. "+nn+"It is a humble request to please reflect this in formation in your records"
        +" It Will be of great help."));
        addEmptyLine(para, 5);
        doc.add(para);
        PdfPTable t=new PdfPTable(2);
        PdfPCell c=new PdfPCell(new Phrase("Categories",cFont));
        c.setBorderColor(BaseColor.BLUE);
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
        c=new PdfPCell(new Phrase("Details",cFont));
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
        t.setHeaderRows(1);
        t.addCell("Prevoius Owner name");
        t.addCell(pn);
        t.addCell("New Owner Name");
        t.addCell(nn);
        t.addCell("New Owner ID");
        t.addCell(i);
        t.addCell("Livestock Type");
        t.addCell(ty);
        t.addCell("Tag of Livestock");
        t.addCell(tn);
        t.addCell("Price of Livestock");
        t.addCell(Integer.toString(p));
        doc.add(t);
        para=new Paragraph(" ");
        addEmptyLine(para,2);
        
        para=new Paragraph("Thanking You"); 
        addEmptyLine(para,2);
        para=new Paragraph("Owner Signature");
        doc.add(para);
    }

    private static void addEmptyLine(Paragraph para, int n) {
        for (int i = 0; i < n; i++) 
            para.add(new Paragraph(" "));
    }
}
